const Events = {
    LoginSendData: 'login-send-data',
    LoginEmitResult: 'login-emit-result',
    LoginIncorrectForm: 'login-incorrect-form',

    SignupSendData: 'signup-send-data',
    SignupEmitResult: 'signup-emit-result',
    SignupIncorrectForm: 'signup-incorrect-form',

    ProfileNewUserLoggedIn: 'profile-new-user-logged-in',
    ProfileFLNameChange: 'profile-flname-change',
    ProfileFLNameResult: 'profile-flname-result',
    ProfileIncorrectFLName: 'profile-incorrect-flname',
    ProfileAvatarChange: 'profile-avatar-change',
    ProfileAvatarResult: 'profile-avatar-result',
    ProfileIncorrectAvatar: 'profile-incorrect-avatar',
    ProfileEmailResult: 'profile-email-result',
    ProfileCheckAuthResult: 'profile-check-auth-result',
    ProfileAllResult: 'profile-all-result',
    ProfileAllGet: 'profile-all-get',
    ProfileLogout: 'profile-logout',
    ProfileLogoutEmitResult: 'profile-logout-emit-result',
    ProfileIncorrectLogout: 'profile-logout-incorrect',
    ProfileTransmitData: 'profile-transmit-user-data',

    ProductsLoad: 'products-load',
    ProductsLoadSearch: 'products-load-search',
    ProductsLoaded: 'products-loaded',
    ProductsChangeCategory: 'products-change-category',
    ProductsItemAdded: 'products-item-added',
    ProductsItemNotAdded: 'products-item-removed',
    ProductsItemFavoriteAdded: 'products-item-favorite',
    ProductsItemFavoriteRemoved: 'products-item-favorite-removed',


    ProductLoad: 'product-load',
    ProductChangeID: 'product-changeID',
    ProductLoaded: 'product-loaded',
    ProductItemNotAdded: 'product-item-not-added',
    ProductItemAdded: 'product-item-added',
    ProductRenderReviewButton: 'product-render-review-button',
    RenderProductReviews: 'render-product-reviews',
    ProductTransmitData: 'product-transmit-data',
    ProductItemFavoriteAdded: 'product-item-favorite',
    ProductItemFavoriteRemoved: 'product-item-favorite-removed',

    HeaderLoad: 'product-load',
    HeaderLoaded: 'product-loaded',
    HeaderChangeCatalogID: 'header-change-catalog-id',
    HeaderChangeCategoryID: 'header-change-category-id',
    HeaderChangeCartItems: 'header-change-cart-items',
    HeaderSetCartItems: 'header-set-cart-items',
    HeaderSetFavoriteItems: 'header-set-favorite-items',
    HeaderChangeFavoriteItems: 'header-change-favorite-items',

    CartAddProduct: 'cart-add-product',
    CartProductChange: 'cart-update-product',
    CartRemoveProduct: 'cart-remove-product',
    CartProductRemoved: 'cart-removed-product',
    CartLoad: 'cart-load',
    CartLoaded: 'cart-loaded',
    CartProductAdded: 'cart-product-added',
    CartLoadProductsAmount: 'cart-load-products-amount',
    CartLoadedProductsAmountReaction: 'cart-loaded-products-amount-reaction',
    CartGetProductsID: 'cart-get-products-ids',
    CartGetProductID: 'cart-get-product-id',
    CartLoadedProductsID: 'cart-loaded-products-ids',
    CartLoadedProductID: 'cart-loaded-product-id',
    CartAddLastProduct: 'cart-add-last-product',
    CartDrop: 'cart-drop',

    OrderLoad: 'order-load',
    OrderLoaded: 'order-loaded',
    OrderNewBill: 'order-new-bill',
    OrderIncorrectPromo: 'order-incorrect-promo',
    SendOrder: 'order-send',

    ReviewRightsLoad: 'review-rights-load',
    ReviewRightsLoaded: 'review-rights-loaded',
    ReviewUserDataLoad: 'review-user-data-load',
    ReviewUserDataLoaded: 'review-user-data-loaded',
    ReviewProductDataLoad: 'review-product-data-load',
    ReviewProductDataLoaded: 'review-product-data-load',
    ReviewOrder: 'review-send',
    GetProductReviews: 'get-product-reviews',
    GetProductReviewsReaction: 'get-product-reviews-reaction',

    ChangeReviewProductId: 'change-review-product-id',
    OrderSent: 'order-sent',

    SendPromo: 'send-promo',
    PromoSent: 'promo-sent',
    RecommendationLoad: 'recommendation-load',
    RecommendationLoaded: 'recommendation-loaded',

    FavoritesLoadProducts: 'favorites-load-products',
    FavoritesAddProduct: 'favorites-add-product',
    FavoritesRemoveProduct: 'favorites-remove-product',
    FavoritesProductsLoaded: 'favorites-products-loaded',
    FavoritesGetProductsID: 'favorites-get-products-id',
    FavoritesGetProductID: 'favorites-get-product-id',
    FavoritesLoadedProductsIDs: 'favorites-loaded-products-ids',
    FavoritesLoadedProductID: 'favorites-loaded-product-id',
    FavoritesProductAdded: 'favorites=product-added',
    FavoritesLoadedProductsAmountReaction: 'favorites-loaded-products-amount-reaction',
    FavoritesLoadProductsAmount: 'favorites-load-products-amount',
    FavoritesProductRemoved: 'favorites-product-removed',
};


export default Events;
